FORMAT: 1A

# CervezaYa API

Documentación de la API para CervezaYa app.

URL: http://api.cervezaya.com

Necesitas autorizarte con los HEADERS:

    X-User-Email: admin@example.com
    X-User-Token: secret

## Usuarios [/users]

### Crear nuevo usuario [POST]

+ Parameters

    + push_uid (string)
    + facebook_uid (string)
    + google_uid (string)
    + username (string) - Campo único
    + email (string) - Campo obligatorio y único
    + publicname (string)
    + avatar (string)
    + custom_avatar (string)
    + gender (string)
    + country (string)
    + city (string)
    + birth (date)
    + active (boolean) - Por defecto 'true'

+ Response 201 (application/json)

        {
            "id": 1,
            "push_uid": null,
            "facebook_uid": null,
            "google_uid": null,
            "email": "demo@example.com",
            "username": "demo",
            "publicname": null,
            "avatar": "",
            "custom_avatar": null,
            "gender": null,
            "birth": null,
            "city": null,
            "country": null
        }

## Usuario [/users/:id]

### Mostrar detalle de usuario [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "push_uid": null,
            "facebook_uid": null,
            "google_uid": null,
            "email": "demo@example.com",
            "username": "demo",
            "publicname": null,
            "avatar": "",
            "custom_avatar": null,
            "gender": null,
            "birth": null,
            "city": null,
            "country": null
        }

### Editar usuario [PUT]

+ Parameters

    + push_uid (string)
    + facebook_uid (string)
    + google_uid (string)
    + username (string) - Campo único
    + email (string) - Campo obligatorio y único
    + publicname (string)
    + avatar (string)
    + custom_avatar (string)
    + gender (string)
    + country (string)
    + city (string)
    + birth (date)
    + active (boolean) - Por defecto 'true'

+ Response 200 (application/json)

        {
            "id": 1,
            "push_uid": null,
            "facebook_uid": null,
            "google_uid": null,
            "email": "demo@example.com",
            "username": "demo",
            "publicname": null,
            "avatar": "",
            "custom_avatar": null,
            "gender": null,
            "birth": null,
            "city": null,
            "country": null
        }

### Eliminar usuario [DELETE]

+ Response 204


## Favoritos de usuario [/users/:user_id/favorites]

### Mostrar favoritos de usuario [GET]

+ Response 200 (application/json)

        [
            {
                "favorite_id": 1,
                "id": 1,
                "name": "La Escondida",
                "address": "Calle Cardenal Bueno Monreal,  30",
                "region": "Sevilla",
                "phone": "954 614 879",
                "rank": 6,
                "latitude": 37.3692168,
                "longitude": -5.9797449,
                "photo": "",
                "user_favorite": false,
                "user_rank": 0,
                "product_name": "Alhambra",
                "product_price": 2.0,
                "product_image": null
            }
        ]

### Crear favorito de usuario [POST]

+ Parameters

    + bar_id (number) - ID del bar

+ Response 201 (application/json)

        {
            "favorite_id": 1,
            "id": 1,
            "name": "La Escondida",
            "address": "Calle Cardenal Bueno Monreal,  30",
            "region": "Sevilla",
            "phone": "954 614 879",
            "rank": 6,
            "latitude": 37.3692168,
            "longitude": -5.9797449,
            "photo": "",
            "user_favorite": false,
            "user_rank": 0,
            "product_name": "Alhambra",
            "product_price": 2.0,
            "product_image": null
        }

## Favorito de usuario [/users/:user_id/favorites/:id]

### Eliminar favorito del usuario [DELETE]

+ Response 204


## Historial de usuario [/users/:user_id/recents]

### Mostrar historial de usuario [GET]

+ Response 200 (application/json)

        [
            {
                "recent_id": 1,
                "id": 1,
                "name": "La Escondida",
                "address": "Calle Cardenal Bueno Monreal,  30",
                "region": "Sevilla",
                "phone": "954 614 879",
                "rank": 6,
                "latitude": 37.3692168,
                "longitude": -5.9797449,
                "photo": "",
                "user_favorite": false,
                "user_rank": 0,
                "product_name": "Alhambra",
                "product_price": 2.0,
                "product_image": null
            }
        ]

### Crear historial o reciente de usuario [POST]

+ Parameters

    + bar_id (number) - ID del bar

+ Response 201 (application/json)

        {
            "recent_id": 1,
            "id": 1,
            "name": "La Escondida",
            "address": "Calle Cardenal Bueno Monreal,  30",
            "region": "Sevilla",
            "phone": "954 614 879",
            "rank": 6,
            "latitude": 37.3692168,
            "longitude": -5.9797449,
            "photo": "",
            "user_favorite": false,
            "user_rank": 0,
            "product_name": "Alhambra",
            "product_price": 2.0,
            "product_image": null
        }


## Valoraciones de usuario [/users/:user_id/ranks]

### Crear valoración de bar por usuario [POST]

+ Parameters

    + value (number) - Valoración de 1 a 10
    + bar_id (number) - ID de bar

+ Response 201 (application/json)

        {
            "rank_id": 1,
            "id": 1,
            "name": "La Escondida",
            "address": "Calle Cardenal Bueno Monreal,  30",
            "region": "Sevilla",
            "phone": "954 614 879",
            "rank": 6,
            "latitude": 37.3692168,
            "longitude": -5.9797449,
            "photo": "",
            "user_favorite": false,
            "user_rank": 0,
            "product_name": "Alhambra",
            "product_price": 2.0,
            "product_image": null
        }

## Valoración de usuario [/users/:user_id/ranks/:id]

### Mostrar valoración de bar por ususario [GET]

+ Response 200 (application/json)

        {
            "rank_id": 1,
            "id": 1,
            "value": 0,
            "name": "La Escondida",
            "address": "Calle Cardenal Bueno Monreal,  30",
            "region": "Sevilla",
            "phone": "954 614 879",
            "rank": 6,
            "latitude": 37.3692168,
            "longitude": -5.9797449,
            "photo": "",
            "user_favorite": false,
            "user_rank": 0,
            "product_name": "Alhambra",
            "product_price": 2.0,
            "product_image": null
        }

### Editar valoración de bar [PUT]

+ Parameters

    + value (number) - Valoración de 1 a 10

+ Response 200 (application/json)

        {
            "rank_id": 1,
            "id": 1,
            "value": 0,
            "name": "La Escondida",
            "address": "Calle Cardenal Bueno Monreal,  30",
            "region": "Sevilla",
            "phone": "954 614 879",
            "rank": 6,
            "latitude": 37.3692168,
            "longitude": -5.9797449,
            "photo": "",
            "user_favorite": false,
            "user_rank": 0,
            "product_name": "Alhambra",
            "product_price": 2.0,
            "product_image": null
        }


## Bares [/bars]

### Mostrar todos los bares [GET]

+ Parameters

    + longitude (number) - Longitud
    + latitude (number) - Latitud
    + min_distance (number) - Mínima distancia
    + max_distance (number) - Máxima distancia
    + min_price (number) - Mínimo precio
    + max_price (number) - Máximo precio
    + user_id (number) - ID de usuario
    + brands_ids (array[number]) - ID de marcas
    + sizes_ids (array[number]) - ID de marcas
    + types_ids (array[number]) - ID de tipos
    + icons (array[number]) - ID de iconos
    + q (string) - Búsqueda por string en nombre o dirección
    + limit (number) - Limita el número de resultados
    + offset (number) - Número de bares que se salta antes de dar el resultado

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "La Escondida",
                "address": "Calle Cardenal Bueno Monreal,  30",
                "region": "Sevilla",
                "phone": "954 614 879",
                "rank": 6,
                "latitude": 37.3692168,
                "longitude": 5.9797449,
                "photo": "",
                "user_favorite": false,
                "user_rank": 6,
                "product_name": null,
                "product_price": 0,
                "product_image": null,
                "is_franchise": true
            }
        ]

## Bar [/bars/:id]

### Mostrar detalle de un único bar [GET]

+ Parameters

    + user_id (number) - ID de usuario

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "La Escondida",
            "description": null,
            "address": "Calle Cardenal Bueno Monreal,  30",
            "region": "Sevilla",
            "phone": "954 614 879",
            "rank": 6,
            "latitude": 37.3692168,
            "longitude": 5.9797449,
            "photo": "",
            "user_favorite_id": 1,
            "user_favorite": false,
            "user_rank": 0,
            "is_franchise": true,
            "products": [
                {
                    "id": 2,
                    "price": 2.0,
                    "brand_name": "Alhambra",
                    "brand_color": "#2b8b2d",
                    "size_icon": 4,
                    "image": "",
                    "image_alt": "",
                    "image_shadow": ""
                }
            ]
        }


## Comentarios de bar [/bars/:bar_id/opinions]

### Mostrar todos los comentarios de bar [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "comment": "Lorem ipsum",
                "time_value": 32,
                "time_unit": "minute",
                "user": {
                    "id": 1,
                    "uid": null,
                    "email": "user@example.com",
                    "publicname": null,
                    "name": " ",
                    "avatar": null,
                    "gender": null,
                    "birth": null,
                    "city": null,
                    "country": null
                }
            }
        ]

### Crear comentario para bar [POST]

+ Parameters

    + comment (string) - Campo obligatorio
    + user_id (number) - ID del usuario
    + published (boolean) - Por defecto 'true'

+ Response 201 (application/json)

        {
            "id": 1,
            "comment": "Lorem ipsum",
            "time_value": 32,
            "time_unit": "minute",
            "user": {
                "id": 1,
                "uid": null,
                "email": "user@example.com",
                "publicname": null,
                "name": " ",
                "avatar": null,
                "gender": null,
                "birth": null,
                "city": null,
                "country": null
            }
        }


## Promociones [/promotions]

### Mostrar todas las promociones [GET]

+ Parameters

    + start_date (string) - fecha en formato YYYY-MM-DD
    + end_date (string) - fecha en formato YYYY-MM-DD
    + date (string) - fecha en formato YYYY-MM-DD, si se usa, anula los anteriores
    + latitude (number) - Latitud
    + longitude (number) - Longitud

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "title": "Promotion 1",
                "description": "Lorem ipsum",
                "image_small": "",
                "image_medium": "",
                "image_large": "",
                "start_date": "2015-05-09 00:00",
                "end_date": "2015-05-25 23:59",
                "recurrent": true,
                "bar": {
                    "id": 3,
                    "name": "Burbujas",
                    "address": "Calle Radio Sevilla,  30",
                    "region": "Sevilla",
                    "phone": "652 345 195",
                    "rank": 0,
                    "latitude": 37.3880527,
                    "longitude": 6.00323509999999,
                    "photo": "",
                    "user_favorite": false,
                    "user_rank": 0,
                    "product_name": null,
                    "product_price": 0,
                    "product_image": null
                }
            }
        ]


## Tipos [/types]

### Mostrar todos los tipos [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Sin Alcohol"
            }
        ]

## Formatos [/sizes]

### Mostrar todos los formatos [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Caña",
                "icon": 1,
                "volume": 20
            }
        ]


## Marcas [/brands]

### Mostrar todas las marcas [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Albero",
                "color": "#8d8e1e",
                "image": "",
                "image_alt": "",
                "image_shadow": ""
            }
        ]

## Contacto del usuario o Feedback [/contacts]

### Mostrar todas las promociones [GET]

+ Parameters

    + user_id (number) - ID del usuario
    + message (string) - texto

+ Response 200 (application/json)

        {
          "id": 1,
          "user_id": 1,
          "message": "Lorem ipsum"
        }
